### ISSUE TITLE
Error processing json or zip file 

### ISSUE THREAD

**Issue by pramod-sec** [TradingDominion/TD-Mesosim-public#1]
Error processing json or zip file

KeyError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/app/td-mesosim/streamlit_app.py", line 663, in <module>
    "underlying_price": item["Vars"]["underlying_price"],

**Comment by TradingDominion** [comment]
I've deployed an updated version of the MesosimTools web app in order to fix the functionality of the Events tab.
This was caused by the latest update of Mesosim removing references to the `underlying_price` due to new license redistribution restrictions from CBOE.
So I've simply removed references and functionality that hooked to that variable.

**Comment by pramod-sec** [comment]
Thank you.
